### ISSUE TITLE
How to get index based data if JSON start with array?

### ISSUE THREAD

**Issue by DeepakDonde** [dchester/jsonpath#109]
Given the example:

`[
  { name: "London", "population": 8615246 },
  { name: "Berlin", "population": 3517424 },
  { name: "Madrid", "population": 3165235 },
  { name: "Rome",   "population": 2870528 }
]`

How can I get `name `at first index?

I am able to get all names by `$..name` but not for the particular index.
I tried `$..[0].name `and other ways but no luck and its not mentioned in document as well.

**Comment by DeepakDonde** [comment]
@sdawood  `$[0].name` is working!
Need to mention this in documentation.
Thanks!!!!

**Comment by sdawood** [comment]
Go ahead and submit a PR, I'm not a maintainer here unfortunately.
