### ISSUE TITLE
Support browser

### ISSUE THREAD

**Issue by vjpr** [dchester/jsonpath#12]

**Comment by alexandernst** [comment]
+1

**Comment by alexandernst** [comment]
I'm working on this and I'm 75% done implementing it. Will make a PR by the end of the day (hopefully).

**Comment by alexandernst** [comment]
I'll write down my progress here:

- [x] Make jsonpath work in the browser (includes durty patching the esprima package)
- [x] Make jsonpath to be require-able with `var jp = require("jsonpath");` in the browser
- [x] Minify
- [ ] Drop underscore (and others?) from the bundle in the browser version and use `_` loaded from `<script>` tags
- [ ] Make the esprima package patching automatic.

**Comment by alexandernst** [comment]
@dchester Can you review my patch and tell me if there is anything wrong so I can fix it? If there isn't, can you merge it and release a new version? (including the browser-compatible code)

**Comment by dchester** [comment]
Nice work -- this is merged in with a few tweaks.  Thanks.

**Comment by jackgeek** [comment]
What browser versions are supported?

**Comment by alexandernst** [comment]
Anything above IE8 should work fine.

**Comment by yanndebelgique** [comment]
This is broken. cannot find esprima module...
