### ISSUE TITLE
Global install fails

### ISSUE THREAD

**Issue by chris-branch** [dchester/jsonpath#122]
If you attempt to install jsonpath globally (or use jsonpath as a dependency in another package that you want to install globally), you may run into a permissions error that prevents the installation from completing successfully.  This occurs if npm has been installed as root so that the global `node_modules` folder is owned by root.  The issue is that jsonpath's `package.json` includes a `postinstall` script that attempts to create a new file, but that is not permitted if the global `node_modules` folder is owned by root.  Current `package.json`:

```
  "scripts": {
    "postinstall": "node lib/aesprim.js > generated/aesprim-browser.js",
    ....
  },
```
This issue has come up before and impacts a number of other packages that use jsonpath as a dependency.  Refer to:

https://github.com/dchester/jsonpath/issues/34
https://github.com/dchester/jsonpath/issues/105

A few workarounds mentioned elsewhere "solve" the problem by including additional flags with the install (e.g., `--unsafe-perm=true --allow-root` or `--ignore-scripts`).  That does avoid the permissions issue, but can cause other issues (e.g., `--ignore-scripts` will ignore _all_ scripts; you can't ignore scripts for one particular dependency, etc.), so this isn't really a good idea.

Fortunately, I think the fix is very simple.  Instead of running a `postinstall` step to generate the `aesprim-browser.js` file during installation, use a `prepublishOnly` script instead so that the file is generated ahead of time and included as part of the package that is published to npm.

**Comment by chris-branch** [comment]
@dchester Any thoughts regarding if/when this PR can be merged?

**Comment by nathankitchen** [comment]
Headache for me in a project that depends on JsonPath too. It can be worked around using `npm install -g {package} --unsafe-perm=true --allow-root`, but that's not a nice way to invite people to install.
