### ISSUE TITLE
how to select according element value

### ISSUE THREAD

**Issue by wanghaisheng** [dchester/jsonpath#21]
for example ,if i  want to select all the books whose isbn =0-553-21311-3
```
$..book[?(@.isbn='0-553-21311-3')] 
```
it does not work

**Comment by toymachiner62** [comment]
:+1:  I'm also trying to figure out how to do this. There's no documentation on this. Help!

**Comment by toymachiner62** [comment]
It seems that double equals is the trick.
```js
$..book[?(@.isbn=='0-553-21311-3')] 
```

https://github.com/dchester/jsonpath/pull/24

**Comment by dchester** [comment]
#24 is merged.
