### ISSUE TITLE
Document extra options for Browserify

### ISSUE THREAD

**Issue by mchelen** [dchester/jsonpath#22]
Hi, I was trying to use this module as a dependency in another Node project, but when I ran Browserify in that project it resulted in the error `Uncaught TypeError: require.resolve is not a function`.

Eventually I found the additional options needed for `jsonpath`:
https://github.com/dchester/jsonpath/blob/855ddc0a1a8138e8361492eb620fca6fe21d6300/Gruntfile.js#L16-L26
https://github.com/dchester/jsonpath/blob/855ddc0a1a8138e8361492eb620fca6fe21d6300/Gruntfile.js#L39-L46

It would help to document this to prevent confusion for anyone else using `jsonpath` as a dependency in a Node project they plan to Browserify.

**Comment by bobby-brennan** [comment]
I'm also hitting ```require.resolve``` issues while trying to use browserify with jsonpath as a nested dependency.

What to I need to add to my Gruntfile to get browserify to run properly?
