### ISSUE TITLE
[Proposal] jp.queryOne

### ISSUE THREAD

**Issue by alexandernst** [dchester/jsonpath#23]
`jp.query` is extremely helpful, but sometimes one needs (and expects) to find only 1 value (for example, when searching by ID). In those cases `jp.query` is wasting precious time iterating over all items, when it could return as soon as a match is found.

This could vastly improve performance whit big sets of data.

**Comment by dchester** [comment]
I think `jp.value()` will do what you want here -- now optimized to stop traversing once it has found the first matching value.  In addition, `jp.query()`, `jp.nodes()`, and `jp.paths()` now take an optional `count` parameter specifying a number of elements to match.

**Comment by alexandernst** [comment]
:+1:
