### ISSUE TITLE
How to use multiple search criteria?

### ISSUE THREAD

**Issue by toymachiner62** [dchester/jsonpath#25]
How can I apply multiple search criteria?

In this example I'd like to get the `name` of the author where the type is `participant` and the `primary` is `false`.

```js
var book = {
  authors: [
    {
      type: 'participant',
      primary: 'false',
      name: 'John'
    },
    {
      type: 'author',
      primary: 'true',
      name: 'Fred'
    }
  ]
}
```

I tried this but to no success
```js
console.log('mars = ', jsonpath.value(book, '$.book.auhors[?(@.type=="participant"),(@.primary=="false")]'));
```

**Comment by toymachiner62** [comment]
I figured it out. The ol' `&&`.

```js
console.log('mars = ', jsonpath.value(book, '$.book.auhors[?(@.type=="participant" && @.primary=="false")]'));
```

**Comment by neelsbr** [comment]
Hey 
Do you have any idea to fetch values using contains in your example?

**Comment by neelsbr** [comment]
Never mind . got it . eg:
jsonpath.query(book, "$..[?(/pa/i.test(@['type']) || /fr/i.test(@['name']))]");
