### ISSUE TITLE
Identifier may contain dashes

### ISSUE THREAD

**Issue by wingedfox** [dchester/jsonpath#27]
Current identifier string contains 
```
identifier: "[a-zA-Z_]+[a-zA-Z0-9_]*"
```
which leads to 
```
$.status.dev-01
-------------^
Expecting 'DOT', 'DOT_DOT', '[', got 'INTEGER'
```
which is wrong as long as "dev-01" key is valid.

**Comment by dchester** [comment]
This is expected behavior in this implementation, mentioned here (5th bullet): https://github.com/dchester/jsonpath#other-minor-differences

To reference a member whose identifier contains a dash, use subscript and quoted string e.g., `$.status['dev-01']`
