### ISSUE TITLE
Better syntax for filter expressions

### ISSUE THREAD

**Issue by anhldbk** [dchester/jsonpath#30]
Currently, we use this syntax to make filters:
```
$..book[?(@.price<30 && @.category=="fiction")]
```

I wonder if we can have a more concise syntax like this one:
```
$..book[@price<30 && @category=="fiction"]
```

It's more natural, right?

**Comment by dchester** [comment]
Your example is definitely more concise, but I'd rather not break compatibility with other existing JSONPath implementations, so I'll go ahead and close.
