### ISSUE TITLE
Support for subscript-descendant-string_literal in handlers

### ISSUE THREAD

**Issue by ianand2** [dchester/jsonpath#31]
Hi
    There is a handler for member-descendant-identifier which helps resolve queries like $..author, which shows all paths where the author key exists from the root node, https://github.com/dchester/jsonpath/blob/master/lib/handlers.js#L45. But if we put the author in quotes, $..['author'], it has no handler (subscript-descendant-string_literal) to resolve it, though the handler is similar. My example is of course very simple, and there was probably a good reason why this is not supported. Just curious to know what that is.

Thanks

**Comment by dchester** [comment]
No good reason this wasn't supported, just an oversight.  Now looking better with d6f70bc0448f3a71017aaa3d3a3d0431fe787727 -- thanks.

**Comment by ianand2** [comment]
very cool. Thanks David, this is a really nifty library.
