### ISSUE TITLE
Error installing the module in Electron

### ISSUE THREAD

**Issue by navy1978** [dchester/jsonpath#34]
I cannot install via npm , if i do that I get this error:

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "install" "jsonpath"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! jsonpath@0.2.4 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsonpath@0.2.4 postinstall script 'node lib/aesprim.js > generated/aesprim-browser.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jsonpath package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/aesprim.js > generated/aesprim-browser.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jsonpath
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jsonpath
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by dchester** [comment]
I'll go ahead and close.  Feel free to reopen if you're able to provide more info.

**Comment by jlongland** [comment]
I'm not the OP, but I stumbled across this as well when running: `npm install jsonpath` on RHEL7, Node 8.1.4 and npm 5.0.3

```
74 silly lifecycle jsonpath@0.2.12~postinstall: Args: [ '-c', 'node lib/aesprim.js > generated/aesprim-browser.js' ]
75 silly lifecycle jsonpath@0.2.12~postinstall: Returned: code: 1  signal: null
76 info lifecycle jsonpath@0.2.12~postinstall: Failed to exec postinstall script
77 verbose unlock done using /root/.npm/_locks/staging-c70fa51f45f02dc6.lock for /opt/canvas-requests/node_modules/.staging
78 verbose stack Error: jsonpath@0.2.12 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
78 verbose stack Exit status 1
78 verbose stack     at EventEmitter.<anonymous> (/usr/local/node/node-v8.1.4/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
78 verbose stack     at emitTwo (events.js:125:13)
78 verbose stack     at EventEmitter.emit (events.js:213:7)
78 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/node-v8.1.4/lib/node_modules/npm/lib/utils/spawn.js:40:14)
78 verbose stack     at emitTwo (events.js:125:13)
78 verbose stack     at ChildProcess.emit (events.js:213:7)
78 verbose stack     at maybeClose (internal/child_process.js:897:16)
78 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
79 verbose pkgid jsonpath@0.2.12
80 verbose cwd /opt/canvas-requests
81 verbose Linux 3.10.0-693.el7.x86_64
82 verbose argv "/usr/local/node/node-v8.1.4/bin/node" "/bin/npm" "install" "jsonpath"
83 verbose node v8.1.4
84 verbose npm  v5.0.3
85 error code ELIFECYCLE
86 error errno 1
87 error jsonpath@0.2.12 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
87 error Exit status 1
88 error Failed at the jsonpath@0.2.12 postinstall script.
88 error This is probably not a problem with npm. There is likely additional logging output above.
89 verbose exit [ 1, true ]
```

If I run the install without the postinstall script, it works:
```
# npm install --ignore-scripts jsonpath
+ jsonpath@0.2.12
added 1 package and removed 3 packages in 1.986s
```

And if I then run the postinstall script, it also works:
`# node lib/aesprim.js > generated/aesprim-browser.js`

Oddly, I didn't encounter this problem on OSX 10.11.6 with Node 8.1.3 and npm 5.0.3.
