### ISSUE TITLE
Invalid calling object in IE 11 - windows 10 users

### ISSUE THREAD

**Issue by neelsbr** [dchester/jsonpath#36]
Hi 
I have used this plugin for json traverse. Getting invalid calling object error in IE11 alone.
Found this line causing error 
function _is_string(obj) {
  return toString.call(obj) == '[object String]';
}

Fixed by changing code like this

function _is_string(obj) {
   var toString = Object.prototype.toString;
  return toString.call(obj) == '[object String]';
}

Please verify from your end. Maybe it will help others

**Comment by dchester** [comment]
Thanks -- this should be better in 0.2.6.

**Comment by neelsbr** [comment]
Thanks for your reply.

I have one doubt in JSON parsing.I have tested below JSON expression to get
matched object. This works fine on this website http://jsonpath.com/ . But
the same expression not bringing any results. I have mentioned both
expression and object. Your help much appreciated. *Also, I want to fetch
matched object using contains condition(like %dgf%,%3535%). Please let me
know if you have any idea.*
*Expression : $..[?(@.code=="610",@.Name=="LINE")]*
*JSON:*
var b = [
{
"code": "00004",
"Name": "UNIQUE",
"display": "00004/UNIQUE"
},
{
"code": "610",
"Name": "LINE",
"display": "610/LINE"
}]

*JSON path code: jsonpath.query(b,'$..[?(@.code=="610",@.Name=="LINE")]').
(this is not working)*

On Sat, Jul 2, 2016 at 3:22 AM, David Chester <notifications@github.com>
wrote:

> Thanks -- this should be better in 0.2.6.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dchester/jsonpath/issues/36#issuecomment-230055579>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGLkoIUIG_WdUcZZSSLQxN_tYnuxZUKJks5qRYw0gaJpZM4JDLE0>
> .
>



-- 
Thanks & Regards,
Neelakandan
