### ISSUE TITLE
Templating using JSONPath expressions

### ISSUE THREAD

**Issue by elyas-bhy** [dchester/jsonpath#37]
This is more of a feature request.
I am trying to achieve the following:

```javascript
var template = {
  message: 'Hello {{$.name}}! You have {{$.messages.length}} new messages.'
};

var data = {
  name: 'Alice',
  messages: [{/*...*/}, {/*...*/}, {/*...*/}]
};

var renderedMessage = jp.render(template, data);
// { "message": "Hello Alice! You have 3 new messages." }
```

The `{{ }}` delimitors and the method name `jp.render` are of course for illustration purposes.
Would this kind of usage be within the scope of this library?

**Comment by dchester** [comment]
If you just want simple templates, you can use [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) directly from ES6 like this:

```js
var template =
  user => `Hello ${user.name}! You have ${user.messages.length} new messages.`;

var data = {
  name: 'Alice',
  messages: [{}, {}, {}]
};

var renderedMessage = template(data);
// Hello Alice! You have 3 new messages.
```

> Would this kind of usage be within the scope of this library?

Yes, I think it would be out of scope.  I'll go ahead and close, but thanks for the thought.
