### ISSUE TITLE
Can't use in Electron while packing with webpack

### ISSUE THREAD

**Issue by Murriouz** [dchester/jsonpath#38]
I'm coding an application that using Electron, and I'm also using webpack to compile my code. 
But when using jsonpath, webpack shows a warning in console:
```
WARNING in ./~/jsonpath/lib/grammar.js
[0]     Critical dependencies:
[0]     4:0-7 require function is used in a way in which dependencies cannot be statically extracted
[0]     4:18-25 require function is used in a way in which dependencies cannot be statically extracted
[0]      @ ./~/jsonpath/lib/grammar.js 4:0-7 4:18-25
```
In Electron's console, there's an error:
```
fs.js:977Uncaught Error: EBADF: bad file descriptor, fstat
fs.fstatSync @ fs.js:977
tryStatSync @ fs.js:462
fs.readFileSync @ fs.js:510
fs.readFileSync @ ELECTRON_ASAR.js:500
(anonymous function) @ grammar.js:104
__webpack_require__ @ bootstrap 31da7ee…:531
fn @ bootstrap 31da7ee…:62
(anonymous function) @ parser.js:1
__webpack_require__ @ bootstrap 31da7ee…:531
fn @ bootstrap 31da7ee…:62
(anonymous function) @ index.js:3
__webpack_require__ @ bootstrap 31da7ee…:531
fn @ bootstrap 31da7ee…:62
(anonymous function) @ index.js:1
__webpack_require__ @ bootstrap 31da7ee…:531
fn @ bootstrap 31da7ee…:62
(anonymous function) @ index.js:12
__webpack_require__ @ bootstrap 31da7ee…:531
fn @ bootstrap 31da7ee…:62
(anonymous function) @ appContainer.js:8
__webpack_require__ @ bootstrap 31da7ee…:531
fn @ bootstrap 31da7ee…:62
(anonymous function) @ shell.js:13
__webpack_require__ @ bootstrap 31da7ee…:531
fn @ bootstrap 31da7ee…:62
(anonymous function) @ bootstrap 31da7ee…:554
__webpack_require__ @ bootstrap 31da7ee…:531
(anonymous function) @ bootstrap 31da7ee…:554
(anonymous function) @ bootstrap 31da7ee…:554
```
When I dig into it, here's the code that causing the error:
```javascript
moduleInclude: fs.readFileSync(require.resolve("../include/module.js")),
actionInclude: fs.readFileSync(require.resolve("../include/action.js"))
```
It's in ```lib/grammar.js```

Here's some code in my js which using jsonpath.
```javascript
import jsonpath from 'jsonpath';

class Point {
...
jsonpath.query(this.object, this.path);
...
}
```

In webpack's config, ```target``` is set to ```electron```, so it won't change ```require``` function, because Electron already offer one.

**Comment by dchester** [comment]
I would suggest using the pre-built `jsonpath.js` library at the root of the repo, instead of asking webpack to build the whole thing from scratch.  Does that work for you?

That `lib/grammar.js` file is really only useful for generating the static `jsonpath` parser itself, not something you probably want at run-time.

**Comment by Murriouz** [comment]
That works for me. Thanks.

**Comment by itaysabato** [comment]
This works but makes Webpack issue a warning:
```
WARNING in ./~/jsonpath/jsonpath.js
Critical dependencies:
3:481-488 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/jsonpath/jsonpath.js 3:481-488
```
Additionally, it does not play nice with typescript imports and [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/36d40a63a05b5cb3413737fbdf7c9a2a26f211fd/jsonpath).

It would make for a much smoother experience if `require('jsonpath')` simply worked with Webpack.

Thanks!

**Comment by janjachacz** [comment]
I'm using the pre-built `jsonpath.js` file but there are some issues..

- When using `$..book[0,1]`, I receive an error `TypeError: _uniq is not a function`.
- When using `$..book[-1:]`, I receive all 5 books instead of the last. Note that `$..book[(@.length-1)]` works as expected.
