### ISSUE TITLE
Filter nodes by array value

### ISSUE THREAD

**Issue by palmerabollo** [dchester/jsonpath#43]
Given a JSON such as:

```json
[
  {
     "type": ["a", "b"]
  },
  {
     "type": ["c"]
  }
]
```

I can't figure out how to get all nodes where type=='c'? Is there a 'contains value' operator or something like that?

Thanks.

**Comment by dchester** [comment]
There is no such "contains value" operator, but you could get there with a filter expression:

```javascript
var nodes = jp.nodes(data, '$..[?(@.type.indexOf("c") > -1)]')
// [ { type: ['c'] } ]
```

**Comment by palmerabollo** [comment]
Thank you.
