### ISSUE TITLE
"proerty:name" problem

### ISSUE THREAD

**Issue by khowling** [dchester/jsonpath#48]
If property name in the json includes a ":", it fails parsing, tried quoting and escaping

"d:Id": [
 "xxxxxxx"
]

content[0].d:Id[0]
------------^
pecting 'DOT', 'DOT_DOT', '[', got 'ARRAY_SLICE'

**Comment by dchester** [comment]
You should have better luck if you use a quoted subscript in the path expression, e.g:

```javascript
jp.query(obj, 'content[0]["d:Id"][0]')
```

In this implementation, property name parts of path expressions follow just about the same rules as property names in JavaScript.  See a bit more explanation here: https://github.com/dchester/jsonpath#other-minor-differences

**Comment by dchester** [comment]
I'll go ahead and close.  Feel free to re-open if this doesn't solve it for you.
