### ISSUE TITLE
Partial String Matching

### ISSUE THREAD

**Issue by iceboxx89** [dchester/jsonpath#49]
Hi,
is there a way i can return nodes where a substring is matched.. like
`$..[?(@.task=~/Cov.*/i)]`
i have tried the above in various combinations but does not seem to return anything.

data:
`[{'item': 'bar', 'group': 'cov001'},{'item': 'foo', 'group': 'cov002'},{'item': 'gee', 'group': 'cog001'}]`

**Comment by bapti** [comment]
@iceboxx89  I've managed to get a regex to work

try

```js
it('Should select cov*', () => {
    var data = [
      { item: "bar", group: "cov001"},
      { item: "foo", group: "cov002"},
      { item: "gee", group: "cog001"}
    ]

    expect( jp.query( data, '$..[?(@.group.match("\cov.+\"))]' ) )
      .to.eql([
        { "group": "cov001", "item": "bar" },
        { "group": "cov002", "item": "foo" }
      ])
  })
```

**Comment by dchester** [comment]
Yes, it's JavaScript syntax in the subscript filters.
