### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by wickedest** [dchester/jsonpath#54]
I noticed that this example is incorrect:

JSONPath                      | Description
------------------------------|------------
`$..book[(@.length-1)]`         | The third book via script subscript

It is not the third book - it is the last book.  The third book would be:

JSONPath                      | Description
------------------------------|------------
`$..book[(@.length-2)]`         | The third book via script subscript

**Comment by dchester** [comment]
Indeed, thanks.  Better with 9f43994ceea9306c9c0b163f857836a5a0c56eba.
