### ISSUE TITLE
Doesn't support quoting of keys that look like paths

### ISSUE THREAD

**Issue by shaunc** [dchester/jsonpath#62]
```
obj = {}
jp.values(obj,'$."a.b"', 1)
```
Throws an error:
```
$."a.b"
---^
Expecting 'STAR', 'IDENTIFIER', 'SCRIPT_EXPRESSION', 'INTEGER', 'END', '[', got 'QQ_STRING'
```
Expected:
```
console.log(obj)
// {'a.b': 1}
```

**Comment by alasdairhurst** [comment]
@shaunc Not sure where jp.values is coming from. That function doesn't seem to be included in this library?
If you want to select a key "a.b" then surely you should be using square brackets?
```
   '$.["a.b"]'
```

**Comment by dchester** [comment]
Yes, you need to use square brackets there for keys containing dot characters, mentioned here: https://github.com/dchester/jsonpath#other-minor-differences

I'll go ahead and close.
