### ISSUE TITLE
Quesiton about consistency

### ISSUE THREAD

**Issue by chazzmoney** [dchester/jsonpath#67]
Given this object:
```
{
  "store": {
    "books": [
      {
        "category": "reference",
        "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95
      },
      {
        "category": "fiction",
        "author": "Evelyn Waugh",
        "title": "Sword of Honour",
        "price": 12.99
      },
      {
        "category": "fiction",
        "author": "Herman Melville",
        "title": "Moby Dick",
        "isbn": "0-553-21311-3",
        "price": 8.99
      },
      {
        "category": "fiction",
        "author": "J. R. R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99
      }
    ],
    "bicycle": {
      "color": "red",
      "price": 19.95
    }
  }
}
```

I would expect that these would be equivalent:
`jsonpath.query(jsObj, '$.store.books[2]')`
`jsonpath.query(jsObj, '$.store.books')[2]`

It turns out these are not equivalent; the first returns [{book2data}] and the second returns undefined.  I was expecting to get {book2data} from both.  It seems like the wrapping array creates the difference and I'm a bit confused as to what the expected behavior is.

Thanks for your thoughts!

**Comment by dchester** [comment]
The `query` method returns an array of matches, so you need to refer to the 0th element even for a single match.  

These are equivalent examples:

```
jp.query(jsObj, '$.store.books[2]')[0]
jp.query(jsObj, '$.store.books')[0][2]
```
