### ISSUE TITLE
Is there a good way to get object and parent attributes?

### ISSUE THREAD

**Issue by cloudtracer** [dchester/jsonpath#77]
I'm struggling to find a decent way to get the parent key name of collection of objects I'm querying for.  For example lets say I have an object formatting like this
```
{
  scans: { 
    scanA: { result: true, value: "xxx"}, 
    scanB: { result: false, value: "yyy"}
  }
}
```

And my query is formatted like this:
`$.scans[?(@.detected === true)].value`

I'd like to be able to get the key name "scanA" along with the value in any of the scans with result "true". 

It doesn't look like this is a supported feature of the JSONPath library, but it would be nice if it was since a fair number of APIs use formatting like this (much to my dismay). 

Any advice on how to query for this data would be appreciated.

**Comment by sflanker** [comment]
Assuming you want to retrieve this information, as opposed to filter on it, you use the [nodes](https://github.com/dchester/jsonpath#jpnodesobj-pathexpression-count) function to retrieve this information. For each matching node, it returns the value and the path to that value. In your case `'scanA'` or `'scanB'` would be retrievable via something like this:

```javascript
    > nodes(data, '$.scans[?(@.result === true)].value')
           .map(function (result) { return { result.path[2]: result.value } })
    [{ 'scanA': 'xxx' }]
```

The path member of the result would look like `['$', 'scans', 'scanA', 'value']`.

**Comment by cloudtracer** [comment]
Sorry it took so long to get back to this.

Finally had a chance to implement it and this totally works for me. Thanks @sflanker
