### ISSUE TITLE
How to get back object after apply?

### ISSUE THREAD

**Issue by mnpenner** [dchester/jsonpath#84]
[`jp.apply`](https://www.npmjs.com/package/jsonpath#jpapplyobj-pathexpression-fn) looks a lot like what I want, but I was hoping to be able to get back the mutated object tree instead of an array of paths. Is that possible?

Basically I have some source JSON that I need to "fix", so the result needs to have the same structure. I guess I can pull out the paths, lop off the first "$" element and then patch up the object, but then I wonder what the purpose of `.apply` is?

**Comment by timo-klarshift** [comment]
@mnpenner as you can find in the tests .apply does directly mutate the input data. See here:
`
test('apply method sets values', function() {
    var data = { a: 1, b: 2, c: 3, z: { a: 100, b: 200 } };
    jp.apply(data, '$..a', function(v) { return v + 1 });
    assert.equal(data.a, 2);
    assert.equal(data.z.a, 101);
  });
`

**Comment by mnpenner** [comment]
@timo-klarshift Oh... maybe when I wrote that I didn't realize it was mutating the object in-place. Looks like it will do what I wanted after all, thanks!
