### ISSUE TITLE
Question: Can we convert the parsed jsonpath object back to standard json object?

### ISSUE THREAD

**Issue by mcafeerun** [dchester/jsonpath#95]
Hi,

This library is super helpful! 

I have a question (not sure if this library is intended for that purpose):

I have a situation where i need to manipulate each and every node value of json object. For this, i'm using **jp.apply()** method. I'm getting the manipulated json as jsonpath object,

```
[ 
......  
  { path: [ '$', 0, 'request' ], value: '33299' },
  { path: [ '$', 0, 'request' ], value: 'Miami' },
  { path: [ '$', 0, 'request' ], value: 'FL' }
........
]
```

Is there a way i can convert it back to standard json object which i passed in to jp.apply()? Eg:
```
[ { request: { 
       zipCode: "33299",
       city: 'Miami',
       stateCode: 'FL'}
}]
```

My code snippet:

            
```
var value = [ { request: { 
       zipCode: '~33299',
       city: 'Miami',
       stateCode: 'FL'}
}]

var parsedData = jp.apply(data, '$..*', function(value) { 
                    if (typeof value === 'string' && value.startsWith('~')){
                        return value.substring(1);
                    } else {
                        return value;
                    }                
                });

```

**Comment by mcafeerun** [comment]
No longer required.. So closing the issue..

**Comment by shahidmau** [comment]
Hi, I am getting the same problem. How did you solve this?
